version: 2.1

jobs:
  build:
    working_directory: /var/www/html/php-website
    docker:
      - image: circleci/php:7.1-node-browsers
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            curl -sS https://getcomposer.org/installer | sudo php -- --install-dir=/usr/local/bin --filename=composer
            composer install --no-ansi --no-interaction --no-progress --no-scripts
      - run:
          name: Deploy to EC2
          command: |
            ssh ubuntu@13.233.227.241 "cd /var/www/html/php-website && git pull origin master"

  runner-test:
    machine: true
    resource_class: shashwat456/circlecirunner
    steps:
      - run: echo "Hi I'm on Runners!"
