version: 2.1

jobs:
  deploy:
    machine:
      enabled: true
    steps:
      - checkout
      - add_ssh_keys:
           fingerprints:
               - "b2:e5:21:05:01:3e:a8:79:13:4a:12:c5:ac:2e:6f:45" 
      - run:
          name: Deploy
          command: |
            ssh -o StrictHostKeyChecking=no ubuntu@15.206.72.86 "cd /var/www/html/php-website && git pull origin master"
workflows:
  build-and-deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: master # only deploy on the main branch
