version: 2.1

jobs:
  deploy:
    machine:
      enabled: true
    steps:
      - run:
          name: Copy ssh key
          command: |
            echo $SSH_PRIVATE_KEY | base64 --decode > ~/.ssh/id_rsa
            chmod 600 ~/.ssh/id_rsa
      - run:
          name: Deploy
          command: |
            ssh -o StrictHostKeyChecking=no ubuntu@13.233.227.241 "cd /var/www/html/php-website && git pull origin master"
workflows:
  build-and-deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: master # only deploy on the main branch
