version: 2.1

jobs:
  deploy:
    machine:
      enabled: true
    steps: 
      - run:
          name: Deploy
          command: |
            ssh -o StrictHostKeyChecking=no ubuntu@15.206.72.86 "cd /var/www/html/php-website && git pull origin master"
          
  runner-test:
    machine: true
    resource_class: shashwat456/circlecirunner
    steps:
      - run: echo "Hi I'm on Runners!"

workflows:
  testing:
    jobs:
      - runner-test
  build-and-deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: master # only deploy on the main branch
