version: 2.1

jobs:
  build:
    # ...
  deploy:
    machine:
      enabled: true
    steps:
      - run:
          name: Deploy Over SSH
          command: |
            ssh SSH_USER@SSH_HOST "cd /var/www/html/php-website && git pull origin master"

workflows:
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build # only deploy once build job has completed
          filters:
            branches:
              only: master # only deploy on the main branch
